version: '3.1'

services:

  postgres:
    container_name: gb-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050

  frontend:
    container_name: gb-frontend
    build: ./frontend
    ports:
      - 8080:80

  backend:
    container_name: gb-backend
    build: ./backend
    environment:
      - ConnectionStrings:GalaxyBoardsDbPostgres=Host=localhost; Database=GalaxyBoards; Username=postgres; Password=secret;
    ports:
      - 7093:80
